name: Publish ryvencore-qt wheel to TestPyPi and PyPi
on:
  create:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist/
        working-directory: ./ryvencore-qt
      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.GH_AC_RCQT_TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ryvencore-qt/dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.GH_AC_RCQT_PYPI_API_TOKEN }}
          packages-dir: ryvencore-qt/dist/
