name: Publish Ryven wheel to PyPi
on:
  create:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  Build-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist/
        working-directory: ./ryven-editor
      # - name: Publish distribution to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.GH_AC_RYVEN_TEST_PYPI_API_TOKEN }}
      #     repository-url: https://test.pypi.org/legacy/
      #     packages-dir: ryven-editor/dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.GH_AC_RYVEN_PYPI_API_TOKEN }}
          packages-dir: ryven-editor/dist/
